
kind: PersistentVolumeClaim
apiVersion: v1beta3
metadata: 
  name: mariadb-volume-claim
  labels:
    name: mariadb-volume-claim
spec: 
  accessModes: 
    - ReadWriteOnce
    - ReadOnlyMany
  resources: 
    requests:
      storage: 2G
    limits:
      storage: 5G
