
kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: mariadb
  labels:
    name: mariadb
spec:
  replicas: 1
  selector:
    name: redis-slave
  template:
    metadata:
      labels:
        name: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.0.17
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            # name must match the volume name below
            - name: mariadb-persistent-storage
              # mount path within the container
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
      volumes:
        - name: mariadb-persistent-storage
          source:
            persistentVolumeClaim:
              claimName: mariadb-volume-claim